/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMapsImageRouteImport } from './routes/api/public/maps-image'

const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMapsImageRoute = ApiPublicMapsImageRouteImport.update({
  id: '/api/public/maps-image',
  path: '/api/public/maps-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calls': typeof CallsRoute
  '/api/public/maps-image': typeof ApiPublicMapsImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calls': typeof CallsRoute
  '/api/public/maps-image': typeof ApiPublicMapsImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calls': typeof CallsRoute
  '/api/public/maps-image': typeof ApiPublicMapsImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/calls' | '/api/public/maps-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/calls' | '/api/public/maps-image'
  id: '__root__' | '/' | '/admin' | '/calls' | '/api/public/maps-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CallsRoute: typeof CallsRoute
  ApiPublicMapsImageRoute: typeof ApiPublicMapsImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maps-image': {
      id: '/api/public/maps-image'
      path: '/api/public/maps-image'
      fullPath: '/api/public/maps-image'
      preLoaderRoute: typeof ApiPublicMapsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CallsRoute: CallsRoute,
  ApiPublicMapsImageRoute: ApiPublicMapsImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
